### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists

### ISSUE THREAD

**Issue by hasuchaudhary** [amitsingh6391/Academic-master#14]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists
![Screenshot (7)](https://user-images.githubusercontent.com/60748650/204204117-668de6a1-ad1c-4411-846a-a7c9236bb09e.png)

Showing This And Screen Splash Only White

**Comment by amitsingh6391** [comment]
fixed now
